---
- src: angstwad.docker_ubuntu
  version: 'v2.0'
- src: franklinkim.git
  version: '1.2.2'
- src: franklinkim.environment
  version: '1.2.0'
- src: cmprescott.chrome
  version: '0.2.2'
- src: geerlingguy.nodejs
  version: '3.3.1'
- src: gantsign.apt
  version: '1.1.3'
- src: gantsign.atom
  version: '1.2.1'
- src: gantsign.atom-packages
  version: '1.0.0'
- src: gantsign.audio
  version: '1.1.2'
- src: https://github.com/gantsign/ansible-role-command-line-tools/archive/1.2.0.tar.gz
  name: gantsign.command-line-tools
- src: gantsign.default-web-browser
  version: '2.0.0'
- src: gantsign.gitkraken
  version: '3.0.0'
- src: gantsign.gnome-proxy
  version: '1.0.0'
- src: gantsign.golang
  version: '1.0.1'
- src: gantsign.inotify
  version: '1.0.0'
- src: gantsign.intellij
- src: gantsign.intellij-plugins
  version: '1.2.0'
- src: gantsign.java
  version: '3.5.0'
- src: gantsign.kubernetes
  version: '1.0.0'
- src: gantsign.lightdm
  version: 'v2.0.1'
- src: gantsign.maven
  version: '3.3.0'
- src: gantsign.maven-color
  version: '4.1.0'
- src: gantsign.maven-notifier
  version: '2.3.0'
- src: gantsign.molecule
  version: '2.1.0'
- src: gantsign.postman
  version: '1.1.0'
- src: gantsign.oh-my-zsh
  version: '1.2.0'
- src: gantsign.pin-to-launcher
  version: '1.2.0'
- src: gantsign.terminator
  version: '1.0.0'
- src: https://github.com/gantsign/ansible-role-unison/archive/1.2.0.tar.gz
  name: gantsign.unison
- src: gantsign.visual-studio-code
- src: gantsign.visual-studio-code-extensions
  version: '1.0.0'
- src: https://github.com/gantsign/ansible-role-xdesktop/archive/2.1.1.tar.gz
  name: gantsign.xdesktop
- src: gantsign.zram-config
  version: '1.1.3'
